; PlatformIO Project Configuration File
; This file defines the build, upload, and library options for the project.
; For detailed documentation, visit: https://docs.platformio.org/page/projectconf.html

[platformio]
description = GuitarAMI

[common]
; Define the platform and framework used for this project
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino

lib_deps =
    https://github.com/Puara/puara-module.git
    https://github.com/cnmat/OSC#3.5.8
    sparkfun/SparkFun BNO080 Cortex Based IMU@^1.1.8
    sparkfun/SparkFun LSM9DS1 IMU@^2.0.0
    https://github.com/UnexpectedMaker/tinypico-helper.git#v1.5
    https://github.com/Puara/puara-gestures.git#ba7987ce6e81ef41d28e3ffd2ed75d784b9fdd37
board_build.partitions = min_spiffs_no_OTA.csv
monitor_speed = 115200
monitor_echo = yes
monitor_filters = default esp32_exception_decoder

; Filesystem options:
; Uncomment one of the following lines to select the filesystem:
board_build.filesystem = littlefs ; Default: LittleFS
;board_build.filesystem = spiffs  ; Use SPIFFS instead (requires -DPUARA_SPIFFS flag)

[env:tinypico]
extends = common
board = tinypico  ; Change board here, ex: tinypico, esp32-c3-devkitc-02, seeed_xiao_esp32s3
build_flags =
    -DBOARD_HAS_PSRAM
    ;-DPUARA_SPIFFS ; indicate the usage of SPIFFS to compiler
    -mfix-esp32-psram-cache-issue ; if using esp32-"c3" boards, comment out this line
    -std=gnu++2a
build_unflags = -std=c++11 -std=c++14 -std=c++17 -std=gnu++11 -std=gnu++14 -std=gnu++17